apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  labels:
    app: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: mayureshkosandar/master:0.2
          ports:
            - containerPort: 8183

---

apiVersion: v1
kind: Service
metadata:
  name: master-svc
spec:
#  type: LoadBalancer
  selector:
    app: master
  ports:
    - port: 8183
      targetPort: 8183
      protocol: TCP