apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-service
  labels:
    app: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master-service
        image: master-service:0.0.1
        ports:
        - containerPort: 8183
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: master-service
spec:
  selector:
    app: master
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8183
    targetPort: 8183
    nodePort: 31110
