spring:
  application:
    name: MASTER-SERVICE
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 3600000
  redis:
    host: 172.21.0.65
    port: 6379
   # password: cnpoc2021
 # test:
   # database:
    #  replace: NONE 




